### ISSUE TITLE
Autonaming sequences

### ISSUE THREAD

**Issue by rolfik** [snuziale/vsts-extension-split-work#11]
When splitting an item, it would be nice to autoname titles by adding a number sufixes etc.:
Example:
- My Work
split into
- My Work - 1
- My Work - 2
then
- My Work - 2
split into
- My Work - 2
- My Work - 3
etc.

**Comment by beccamc** [comment]
The split dialog allows you to name the new work item. This give you the flexibility to name things -1, or whatever you want.
