### ISSUE TITLE
Does not work when state names are customized

### ISSUE THREAD

**Issue by pawelpr** [snuziale/vsts-extension-split-work#16]
Hello,
This extension uses hard coded names of "closed" states. It is hard coded in scripts/dialog.tsx line 12:
var ExcludedWorkItemStates = ["Closed", "Removed", "Cut", "Done", "Completed"];

But in real world these names can be customized in TFS process template and then identified as "closed" in ProcessConfiguration.xml file.

Please get the names of closed states from that place to make it working with customized configurations.

**Comment by beccamc** [comment]
This is fixed with version 1.5
