### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by pabrams** [snuziale/vsts-extension-split-work#18]
I cloned the repo, ran `npm install`, then `grunt build`, and I get the following:

> C:\Users\Paul.Abrams\Source\Repos\split-extension>grunt build
> Running "ts:build" (ts) task
> Compiling...
> Using tsc v1.8.9
> node_modules/vss-web-extension-sdk/typings/vss.d.ts(21866,29): error TS1005: '='
>  expected.
> node_modules/vss-web-extension-sdk/typings/vss.d.ts(21874,21): error TS1005: '='
>  expected.
> node_modules/vss-web-extension-sdk/typings/vss.d.ts(21874,30): error TS1005: ';'
>  expected.
> node_modules/vss-web-extension-sdk/typings/vss.d.ts(21875,21): error TS1005: '='
>  expected.
> node_modules/vss-web-extension-sdk/typings/vss.d.ts(21875,41): error TS1005: ';'
>  expected.
> node_modules/vss-web-extension-sdk/typings/vss.d.ts(21876,29): error TS1005: '='
>  expected.
> node_modules/vss-web-extension-sdk/typings/vss.d.ts(29398,21): error TS1005: '='
>  expected.
> node_modules/vss-web-extension-sdk/typings/vss.d.ts(29398,45): error TS1005: ';'
>  expected.
> 
> >> 8 syntax errors
> >> Error: tsc return code: 2
> Warning: Task "ts:build" failed. Use --force to continue.
> 
> Aborted due to warnings.

**Comment by beccamc** [comment]
This is now fixed! Grunt build works.
