### ISSUE TITLE
Does not handle nordic letters in subject field

### ISSUE THREAD

**Issue by svammelsurium** [snuziale/vsts-extension-split-work#19]
No split occurs when subject field contains nordic letters ...

**Comment by beccamc** [comment]
I just tested this with "ø æ ø å Æ Ø Å" in both the title and description. I successfully split the work item. 

We just fixed a bunch of issues, including...
- Not working on chrome
- Not working with required field
- Not working with custom closed/removed states

Maybe one of these was the real issue? Did you see any console errors?
