### ISSUE TITLE
Menu item doesn't work (VSTS / Firefox 46.0.1) 

### ISSUE THREAD

**Issue by pascalberger** [snuziale/vsts-extension-split-work#2]
I installed the extension in our VSTS account. When opening the menu of a work item the menu item appears, but the text is missing:

![untitled](https://cloud.githubusercontent.com/assets/2190718/15642122/97bef97a-2645-11e6-8e35-adf245e4d627.png)

Also clicking on the item doesn't start any operation (also no error logged in console)

**Comment by snuziale** [comment]
Thanks for reporting the issue -- it appears to be an issue with the contribution on the work item form context menu.  I'll have a look into it.
The ideal experience is to use the cards experience from the kanban board:
![image](https://cloud.githubusercontent.com/assets/6452957/15655633/b10e4440-2653-11e6-98d0-631b2d339db5.png)

**Comment by snuziale** [comment]
This was fixed/pushed and the extension on the marketplace was updated.  Thanks.

**Comment by pascalberger** [comment]
Thanks @snuziale. The extension in the marketplace is still at version 0.1.0. You need to increment the version number to have it updated in the tenants where it is installed.

**Comment by snuziale** [comment]
@pascalberger it has been updated. Thanks.
