### ISSUE TITLE
Split failing due to TF401320 error on custom field.

### ISSUE THREAD

**Issue by Falconwmua** [snuziale/vsts-extension-split-work#25]
Split is failing with 400 

>{"$id":"1","customProperties":{"FieldReferenceName":null,"FieldStatusFlags":"none","ErrorMessage":"TF401320: Rule Error for field Injected. Error code: Required, InvalidEmpty. One additional error occurred during validation of the work item. Please correct all errors and try again.","FieldStatusCode":0,"RuleValidationErrors":[{"fieldReferenceName":"ABLScrum.Injected","fieldStatusFlags":"required, invalidEmpty","errorMessage":"TF401320: Rule Error for field Injected. Error code: Required, InvalidEmpty.","fieldStatusCode":524289,"ruleValidationErrors":null},{"fieldReferenceName":"ABLScrum.SecurityIssue","fieldStatusFlags":"required, invalidEmpty","errorMessage":"TF401320: Rule Error for field SecurityIssue. Error code: Required, InvalidEmpty.","fieldStatusCode":524289,"ruleValidationErrors":null}]},"innerException":null,"message":"TF401320: Rule Error for field Injected. Error code: Required, InvalidEmpty. One additional error occurred during validation of the work item. Please correct all errors and try again.","typeName":"Microsoft.TeamFoundation.WorkItemTracking.Server.RuleValidationException, Microsoft.TeamFoundation.WorkItemTracking.Server","typeKey":"RuleValidationException","errorCode":0,"eventId":3200}

The fields are a custom field that is a boolean.

**Comment by jonvestnb** [comment]
We are experiencing this same issue.  Split fails due to custom Boolean fields.

**Comment by beccamc** [comment]
Sorry for my delay on this. The problem was on the value assignment for this field (value = value || ""). For false booleans an empty string is passed to the server, which fails validation.
 
I've a PR up to fix. Technically, this would still be a problem for fields of other types that are undefined. However, if its a required field it can't be undefined, so this fix should be okay.
