### ISSUE TITLE
Don't work on TFS 2015 update 2 on-premises.

### ISSUE THREAD

**Issue by smeysam** [snuziale/vsts-extension-split-work#3]
Hi
I am using TFS 2015.2 on-premises.
I was download the Split and upload to my team project. but it is not work! as you can see in Fig.
![e2](https://cloud.githubusercontent.com/assets/19660193/15663527/58d18c6a-2711-11e6-9dcb-70852ffc4234.jpg)
![e1](https://cloud.githubusercontent.com/assets/19660193/15663531/61ab6c16-2711-11e6-9685-4447c69c11d2.jpg)

the Split option does not added to menu!

**Comment by snuziale** [comment]
Can you confirm the Split extension is "Enable" -- based on your screenshot I could argue that Split and Team Calendar extension are not enabled...

**Comment by smeysam** [comment]
Hi Snuziale.
excuse me. I was forget that enable this. **But** before are take picture it was enable, when I see that it is not working disabled it, and also "Team Calendar".
When enable does not work yet.!

**Comment by smeysam** [comment]
I said that Enable but not working yet!
![e3](https://cloud.githubusercontent.com/assets/19660193/15672264/e8dce8b2-2744-11e6-8b4e-9ad030673ff3.jpg)
![e4](https://cloud.githubusercontent.com/assets/19660193/15672269/ed45207c-2744-11e6-90c8-637600ef144c.jpg)

**Comment by snuziale** [comment]
This has been fixed and the extension version is now 0.1.1 - and its published.

**Comment by smeysam** [comment]
Hi
very thanks, that's OK.

**Comment by snuziale** [comment]
Would be great if you could update your review :)
