### ISSUE TITLE
Unable to Split a Feature work item type

### ISSUE THREAD

**Issue by jhughesgit** [snuziale/vsts-extension-split-work#4]
UPDATE: see additional comment below for more defect details.

When attempting to split a Feature work item type, the "Split" button has no effect. The button appears to clean (css color changes occur) but the popup does not change or disappear and no error message is show... nothing happens. Repeated clicking on the button also has no effect. Changing the Title, selected PBI childres, and the checkbox and clicking the split button also has no effect. Clicking the Cancel button does cause the popup to disappear.

It appears that Split only works on PBIs and Bugs.

![image](https://cloud.githubusercontent.com/assets/18475640/17496233/f42587ec-5d81-11e6-9dfc-622acadab298.png)

**Comment by PCurd** [comment]
Same happens to me on User Stories.

**Comment by jhughesgit** [comment]
In reviewing the issue more, I found that Split does not support work item types with custom fields that are marked as required. When the request to create the new work item, only the basic fields like title, area path, etc are passed, no custom fields are passed.

Can someone please add support for custom fields?

**Comment by beccamc** [comment]
This is fixed in version 1.5!
